FROM node:18-alpine

WORKDIR /app

COPY package*.json ./
RUN npm ci --only=production

COPY packages/ ./packages/
COPY apps/worker/ ./apps/worker/

RUN npm run build:surge-worker

CMD ["node", "dist/apps/worker/src/surge.worker.js"]